#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019-2021 Dominik Salvet
# Copyright 2019 Alexander Agura
# https://github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------

echo 'disabling systemd service' &&
systemctl -q disable afc.service

echo 'removing files' &&
rm -f /usr/local/bin/asus-fan-control \
      /etc/bash_completion.d/afc-completion \
      /usr/share/asus-fan-control/models \
      /etc/systemd/system/afc.service &&

# remove also AFC directory if possible
{ rmdir /usr/share/asus-fan-control/ 2>/dev/null; true; }
