#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# Copyright 2019 Alexander Agura
# https://github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------

echo 'disabling systemd service'
systemctl -q disable asus-fan-control.service

echo 'removing files'
rm -f /usr/local/bin/asus-fan-control \
      /etc/bash_completion.d/asus-fan-control-completion.bash \
      /usr/share/asus-fan-control/models \
      /etc/systemd/system/asus-fan-control.service
