#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------

# run asus-fan-control after boot
systemctl enable asus-fan-control.service &&

# try to apply changes immediately
{ asus-fan-control; true; } # not a problem if it fails
