#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# Copyright 2019 Alexander Agura
# github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------

# run asus-fan-control after boot
systemctl -q enable asus-fan-control.service &&

# try to apply changes immediately
if ! asus-fan-control; then
    echo 'failed to apply changes immediately' >&2 # do not return fail, though
fi
