#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# Copyright 2019 Alexander Agura
# https://github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------

# run asus-fan-control after boot
systemctl -q enable asus-fan-control.service

# load acpi_call
if command -v modprobe > /dev/null; then
    if modprobe -n acpi_call 2>/dev/null; then
        modprobe acpi_call
    fi
fi

# try to apply changes immediately
if ! asus-fan-control; then
    echo 'failed to apply changes immediately' >&2
fi

true # always succeed (as reboot may help)
