#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------


# dependencies are not installed by default
installed=false &&

# check whether dependencies can be installed automatically
if command -v apt-get > /dev/null; then
    # install acpi_call kernel module to make ACPI calls
    apt-get install -y acpi-call-dkms > /dev/null &&
    installed=true # acpi_call installed
fi &&

# if dependencies have been installed
if "$installed"; then
    # load acpi_call at boot
    if [ ! -f /etc/modules ]; then
        echo acpi_call > /etc/modules
    elif ! grep -q '^acpi_call$' /etc/modules; then
        echo acpi_call >> /etc/modules
    fi &&

    # load acpi_call immediately
    if command -v modprobe > /dev/null; then
        modprobe acpi_call; true # not a problem if it fails
    fi
fi
