#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# Copyright 2020 Alexander Agura
# https://github.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------

# default commands state
apt_get_present=false
dpkg_present=false
# mark callable commands as present
if command -v apt-get > /dev/null; then apt_get_present=true; fi
if command -v dpkg > /dev/null; then dpkg_present=true; fi

# install dmidecode
if [ "$OFFLINE_MODE" = true ]; then
    if [ "$dpkg_present" = true ]; then
        if ! dpkg -l dmidecode > /dev/null 2>&1; then
            echo 'cannot install dmidecode in offline mode' >&2; exit 1
        fi
    fi
elif [ "$apt_get_present" = true ]; then
    apt-get install -y dmidecode > /dev/null
fi &&

# install acpi-call-dkms
if [ "$OFFLINE_MODE" = true ]; then
    if [ "$dpkg_present" = true ]; then
        if ! dpkg -l acpi-call-dkms > /dev/null 2>&1; then
            echo 'cannot install acpi-call-dkms in offline mode' >&2; exit 1
        fi
    fi
elif [ "$apt_get_present" = true ]; then
    apt-get install -y acpi-call-dkms > /dev/null
fi
