#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2017-2018 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://gitlab.com/dominiksalvet/asus-fan-control
#-------------------------------------------------------------------------------
# PARAMETERS:
#   $1 - installation directory path
#   $2 - source directory path
#   $3 - target data directory path
#   $4 - source data directory path
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# SOFTWARE DEPENDENCIES
#-------------------------------------------------------------------------------

# list of required software
SW_REQUIRED='command echo [ id grep chmod sed cp ls mkdir'

# check if some software is missing
for i in $SW_REQUIRED; do
    # software is missing if at least one piece of software is missing
    if ! command -v "$i" > /dev/null; then
        echo "$0: Required software $i is missing.
POSSIBLE SOLUTIONS:
  * Use command 'sudo apt install $i'." >&2
        exit 1
    fi
done

#-------------------------------------------------------------------------------
# DEFINITIONS
#-------------------------------------------------------------------------------

INSTALL_DIR="$1"

# escape delimiters of the installation directory path for later use in a sed script
INSTALL_DIR_ESCAPED="$(echo "$INSTALL_DIR" | sed -E -e 's|/|\\/|g')"

SRC_DIR="$2"

# sed script - regular expression of line containing a successful exit of a shell script
CONTAINS_EXIT_0='^[[:blank:]]*exit(|[[:blank:]]+0+)([[:blank:]]*|[[:blank:]]+#.*)$'

TAR_DATA_DIR="$3"

SRC_DATA_DIR="$4"

#-------------------------------------------------------------------------------
# CHECK STATE
#-------------------------------------------------------------------------------

# check if the installation directory argument passed
if [ -z "$INSTALL_DIR" ]; then
    echo "$0: Please supply non-empty installation directory argument." >&2
    exit 1
fi

# check if the installation directory exists
if [ ! -d "$INSTALL_DIR/" ]; then
    echo "$0: Installation directory '$INSTALL_DIR/' doesn't exist.
POSSIBLE SOLUTIONS:
  * Create '$INSTALL_DIR/' and repeat the action." >&2
    exit 1
fi

# check if installed
if [ -x "$INSTALL_DIR/asus-fan-control" ]; then
    echo 'The program is already installed in the given installation directory.'
    exit 0
fi

# check if the source directory argument passed
if [ -z "$SRC_DIR" ]; then
    echo "$0: Please supply non-empty source directory argument." >&2
    exit 1
fi

# check if source directory exists and is not empty
if [ ! -d "$SRC_DIR/" ] || [ -z "$(ls -A "$SRC_DIR/")" ]; then
    echo "$0: Source directory '$SRC_DIR/' must exist and must not be empty." >&2
    exit 1
fi

# check if the data directory argument passed
if [ -z "$TAR_DATA_DIR" ]; then
    echo "$0: Please supply non-empty data directory argument." >&2
    exit 1
fi

# check if the data directory argument passed
if [ -z "$SRC_DATA_DIR" ]; then
    echo "$0: Please supply non-empty data directory argument." >&2
    exit 1
fi

# check if data directory exists and is not empty
if [ ! -d "$SRC_DATA_DIR/" ] || [ -z "$(ls -A "$SRC_DATA_DIR/")" ]; then
    echo "$0: Data directory '$SRC_DATA_DIR/' must exist and must not be empty." >&2
    exit 1
fi

#-------------------------------------------------------------------------------
# INSTALLATION
#-------------------------------------------------------------------------------

# check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "$0: Please run as root." >&2
    exit 1
fi

# create '/etc/rc.local' if it does not exist
if [ ! -f /etc/rc.local ]; then
    echo '#!/bin/sh -e

exit 0' > /etc/rc.local
    echo "'/etc/rc.local' has been created."
# append a successful exit if it does not contain one
elif ! grep -q -E -e "$CONTAINS_EXIT_0" /etc/rc.local; then
    echo 'exit 0' >> /etc/rc.local
    echo "'/etc/rc.local' has been modified to contain a successful exit."
fi
# set the execution permission of '/etc/rc.local'
chmod a+x /etc/rc.local

# copy program's static data
mkdir -p "$TAR_DATA_DIR/" &&
cp -T -R "$SRC_DATA_DIR/" "$TAR_DATA_DIR/" &&
# copy the program itself
cp "$SRC_DIR/asus-fan-control" "$INSTALL_DIR/" &&
chmod a+x "$INSTALL_DIR/asus-fan-control" &&
# add script calling to '/etc/rc.local' file to run the program after boot
sed -i -E -e '/'"$CONTAINS_EXIT_0"'/{s//'"'$INSTALL_DIR_ESCAPED"'\/asus-fan-control'"'"'\n&/; :add_line; N; badd_line}' /etc/rc.local || {
    echo "$0: Can't finish the installation.
POSSIBLE SOLUTIONS:
  * Try install asus-fan-control again.
  * Free up some storage space.
  * Contact an asus-fan-control developer." >&2
    exit 1
}

# apply the changes immediately (if install-deps hasn't been run before, it may be unsuccessful)
"$INSTALL_DIR"/asus-fan-control > /dev/null 2>/dev/null || {
    echo "$0: Can't apply the changes immediately.
POSSIBLE SOLUTIONS:
  * Reboot your device." >&2
}

exit 0
