#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2017-2018 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://gitlab.com/dominiksalvet/ux430ua-fan-control
#-------------------------------------------------------------------------------
# PARAMETERS:
#   $1 - installation directory path
#   $2 - build directory path
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# SOFTWARE DEPENDENCIES
#-------------------------------------------------------------------------------

# list of required software
SW_REQUIRED='command echo [ id grep chmod sed cp'

# check if some software is missing
for i in $SW_REQUIRED; do
    # software is missing if at least one piece of software is missing
    if ! command -v "$i" > /dev/null; then
        echo "$0: Required software $i is missing.
POSSIBLE SOLUTIONS:
  * Use command 'sudo apt install $i'." >&2
        exit 1
    fi
done

#-------------------------------------------------------------------------------
# DEFINITIONS
#-------------------------------------------------------------------------------

INSTALL_DIR="$1"

# escape delimiters of the installation directory path for later use in a sed script
INSTALL_DIR_ESCAPED="$(echo "$INSTALL_DIR" | sed -E -e 's|/|\\/|g')"

BUILD_DIR="$2"

# sed script - regular expression of line containing a successful exit of a shell script
CONTAINS_EXIT_0='^[[:blank:]]*exit(|[[:blank:]]+0+)([[:blank:]]*|[[:blank:]]+#.*)$'

#-------------------------------------------------------------------------------
# CHECK STATE
#-------------------------------------------------------------------------------

# check if the installation directory argument passed
if [ -z "$INSTALL_DIR" ]; then
    echo "$0: Please supply non-empty installation directory argument." >&2
    exit 1
fi

# check if the installation directory exists
if [ ! -d "$INSTALL_DIR/" ]; then
    echo "$0: Installation directory '$INSTALL_DIR/' doesn't exist.
POSSIBLE SOLUTIONS:
  * Create '$INSTALL_DIR/' and repeat the action." >&2
    exit 1
fi

# check if already installed
if [ -f "$INSTALL_DIR/ux430ua-fan-control" ]; then
    echo 'The program is already installed.'
    exit 0
fi

# check if the build directory argument passed
if [ -z "$BUILD_DIR" ]; then
    echo "$0: Please supply non-empty build directory argument." >&2
    exit 1
fi

# check if ux430ua-fan-control file exists
if [ ! -f "$BUILD_DIR/ux430ua-fan-control" ]; then
    echo "$0: '$BUILD_DIR/ux430ua-fan-control' does not exist.
POSSIBLE SOLUTIONS:
  * Download the project again and repeat the action." >&2
    exit 1
fi

#-------------------------------------------------------------------------------
# INSTALLATION
#-------------------------------------------------------------------------------

# check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "$0: Please run as root." >&2
    exit 1
fi

# create '/etc/rc.local' if it does not exist
if [ ! -f /etc/rc.local ]; then
    echo '#!/bin/sh -e

exit 0' > /etc/rc.local
    echo "'/etc/rc.local' has been created."
# append a successful exit if it does not contain one
elif ! grep -q -E -e "$CONTAINS_EXIT_0" /etc/rc.local; then
    echo 'exit 0' >> /etc/rc.local
    echo "'/etc/rc.local' has been modified to contain a successful exit."
fi
# set the execution permission of '/etc/rc.local'
chmod a+x /etc/rc.local

# copy the program itself
cp "$BUILD_DIR/ux430ua-fan-control" "$INSTALL_DIR/" &&
# add script calling to '/etc/rc.local' file to run the program after boot
sed -i -E -e '/'"$CONTAINS_EXIT_0"'/{s//'"'$INSTALL_DIR_ESCAPED"'\/ux430ua-fan-control'"'"'\n&/; :add_line; N; badd_line}' /etc/rc.local || {
    echo "$0: It wasn't possible to finish the installation.
POSSIBLE SOLUTIONS:
  * Free up some storage space.
  * Contact a ux430ua-fan-control developer." >&2
    exit 1
}

# apply the changes immediately (it may not be successful as the program dependencies may be missing)
echo 'Trying to apply the changes immediately.'
"$INSTALL_DIR"/ux430ua-fan-control

exit 0
