#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2018 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://gitlab.com/dominiksalvet/ux430ua-fan-control
#-------------------------------------------------------------------------------
# PARAMETERS:
#   $1 - installation directory path
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# SOFTWARE DEPENDENCIES
#-------------------------------------------------------------------------------

# list of required software
SW_REQUIRED='command echo [ rm sed'

# check if some software is missing
for i in $SW_REQUIRED; do
    # software is missing if at least one piece of software is missing
    if ! command -v "$i" > /dev/null; then
        echo "$0: Required software $i is missing.
POSSIBLE SOLUTIONS:
  * Use command 'sudo apt install $i'." >&2
        exit 1
    fi
done

#-------------------------------------------------------------------------------
# DEFINITIONS
#-------------------------------------------------------------------------------

INSTALL_DIR="$1"

# escape delimiters of the installation directory path for later use in a sed script
INSTALL_DIR_ESCAPED="$(echo "$INSTALL_DIR" | sed -E -e 's|/|\\/|g')"

#-------------------------------------------------------------------------------
# CHECK STATE
#-------------------------------------------------------------------------------

# check if the installation directory argument passed
if [ -z "$INSTALL_DIR" ]; then
    echo "$0: Please supply non-empty installation directory argument." >&2
    exit 1
fi

# check if not installed
if [ ! -x "$INSTALL_DIR/ux430ua-fan-control" ]; then
    echo 'The program is not installed in the given installation directory.'
    exit 0
fi

#-------------------------------------------------------------------------------
# UNINSTALLATION
#-------------------------------------------------------------------------------

# check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "$0: Please run as root." >&2
    exit 1
fi

# remove all lines calling the program from '/etc/rc.local'
sed -i -E -e '/^[[:blank:]]*'"('$INSTALL_DIR_ESCAPED.*\/ux430ua-fan-control'|$INSTALL_DIR_ESCAPED.*\/ux430ua-fan-control)"'(| .*)$/d' /etc/rc.local &&
# remove the program itself
rm -f "$INSTALL_DIR/ux430ua-fan-control" || {
    echo "$0: Can't finish the uninstallation.
POSSIBLE SOLUTIONS:
  * Contact a ux430ua-fan-control developer." >&2
    exit 1
}
